### ISSUE TITLE
parse_alpscore_data.py Pandas problem

### ISSUE THREAD

**Issue by egull** [CQMP/scripts#1]
I'm getting a problem when importing on a machine that has pandas, see below: it looks like the header skip of the ALPSCore H5GF header is not done properly.

this is the offending line:
data1 = pandas.read_table(fname, parse_dates = False, header = 0 if has_header else None, delim_whitespace = True)

switching off pandas and going with getfromtxt works without flaws.

Is anybody using Pandas? Sergei?

[egull@flux-login1 U8.0_beta5_mu0.00_it0_inverter]$ python $HOME/scripts/dmft_to_opendf/parse_alpscore_data.py --vertex vert_F_phpp --nbosonic 32 --nfermionic 64 --gw ../U8.0_beta5_mu0.00_it0/G_omega_16 --sigma ../U8.0_beta5_mu0.00_it0/selfenergy_16
Parsing data with the following parameters
gw : ../U8.0_beta5_mu0.00_it0/G_omega_16
plaintext : 0
vertex : vert_F_phpp
nfermionic : 64
mu : 0.0
sigma : ../U8.0_beta5_mu0.00_it0/selfenergy_16
nbosonic : 32
--> Loading ../U8.0_beta5_mu0.00_it0/G_omega_16
file has a header; using panda read
data: [['#' '#' '0.62831853071796' ..., '1283.6547582568' '1284.9113953182'
  '1286.1680323797']
 ['MOMENTUM_INDEX' 'INDEX' '-0.015010425326786' ..., '1.1876081902645e-08'
  '1.2034198426033e-08' '1.2066065504235e-08']
 ['mesh:' 'mesh:' '-0.24698901822977' ..., '-0.00077901673648843'
  '-0.00077825487169563' '-0.0007774924975589']
 ...,
 ['points:' nan nan ..., nan nan nan]
 ['(0,0)' nan nan ..., nan nan nan]
 [nan nan nan ..., nan nan nan]]
shape : (10, 1026)
1d data, [    9.  1025.] dimensions, real data
Traceback (most recent call last):
  File "/home/egull/scripts/dmft_to_opendf/parse_alpscore_data.py", line 187, in <module>
    main(vars(args))
  File "/home/egull/scripts/dmft_to_opendf/parse_alpscore_data.py", line 22, in main
    (gw_grids, gw_data_in) = read_txt(params["gw"])
  File "/home/egull/scripts/dmft_to_opendf/parse_alpscore_data.py", line 155, in read_txt
    return convert_multidimensional(all_data)
  File "/home/egull/scripts/dmft_to_opendf/parse_alpscore_data.py", line 126, in convert_multidimensional
    array_out = np.reshape(data_out,shape_out)
  File "/sw/lsa/centos7/python-anaconda2/latest/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 225, in reshape
    return reshape(newshape, order=order)

**Comment by iskakoff** [comment]
Yeah, I know this problem. I have got this for DCA version of this scripts I have written and just disable panda support in my case. By the way, I have pushed the fix.

I don't know why this
`has_header = not np.all([isfloat(x) for x in open(fname,'rb').readline().split()])`
was specified as header for pandas. I have changed header to None and added comment="#".
Now it works, at least for me.
